### ISSUE TITLE
The reserved indicator "@" cannot start a plain scalar

### ISSUE THREAD

**Issue by Avariya** [beryllium/CacheBundle#26]
While running PHPUnit tests got current error:

```
Caused by
Symfony\Component\Yaml\Exception\ParseException: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 14 (near "arguments: [@beryllium_cache.client.memcache]").

E:\restapi\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Loader\YamlFileLoader.php:355
E:\restapi\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Loader\YamlFileLoader.php:44
E:\restapi\vendor\Beryllium\CacheBundle\Beryllium\CacheBundle\DependencyInjection\BerylliumCacheExtension.php:26
E:\restapi\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass.php:55
E:\restapi\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass.php:39
E:\restapi\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\Compiler.php:107
E:\restapi\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php:589
E:\restapi\app\bootstrap.php.cache:2687
E:\restapi\app\bootstrap.php.cache:2465
E:\restapi\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Test\KernelTestCase.php:142
E:\restapi\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Test\WebTestCase.php:33
```

Can you quote all parameters in service.yml started from @
For example:
arguments: [@beryllium_cache.client.memcache]
change to
arguments: ['@beryllium_cache.client.memcache']
It really helps. Thank you.

**Comment by beryllium** [comment]
What version of Symfony are you trying to run this under? I tried linting the yaml file with Symfony 2.8's built-in linter and it declared the file valid. After that I tried installing it in a symfony 3.0 project and composer freaked out and wouldn't let me, so the bundle currently appears not to be compatible with Symfony 3.0.

The symfony 3.0 linter did present the same errors you're seeing, but the fact that composer can't install the bundle under SF3 indicates that more work is needed overall before it can support SF3.

**Comment by Avariya** [comment]
I have version 2.8 currently.
Bundle works perfectly in dev and prod except of PHPUnit part where all tasts failing becourse of this Notice-like message.
Also in [manual page](http://symfony.com/doc/2.8/book/service_container.html) all examples argument with service are quoted.

**Comment by beryllium** [comment]
OK, I've pushed an update into the master branch, please let me know if this fixes the issue.

**Comment by Avariya** [comment]
Now all works without any problems.
Thank you for your help.
